version: "3.9"
services:
  api:
    build: ./apps/api
    environment:
      PORT: "8080"
      DB_HOST: db
      DB_PORT: "5432"
      DB_USER: core
      DB_PASS: corepass
      DB_NAME: corebank
      OUTPUT_DIR: "/mnt/e/outputs/ingest"
      # CRON opcional para promoción automática staging→ledger:
      # CRON_PROMOTE: "1"
      # PROMOTE_BATCH: "5000"
      # CRON_EXPR: "*/5 * * * *"
    ports: ["8080:8080"]
    volumes:
      - "E:/:/mnt/e"

  dashboard:
    build: ./apps/dashboard
    environment:
      NEXT_PUBLIC_API_BASE: http://api:8080
      NEXT_PUBLIC_WS_URL: ws://api:8080/ws
      NEXT_PUBLIC_APP_VERSION: 1.0.0
      NEXT_PUBLIC_APP_NAME: Core Banking Dashboard
      NODE_ENV: development
      NEXT_TELEMETRY_DISABLED: "1"
    ports: ["3000:3000"]
    depends_on:
      - api

  ingest:
    build: ./services/ingest-dtc1b
    environment:
      INPUT_PATH: /mnt/e/dtc1b
      OUTPUT_DIR: /mnt/e/outputs/ingest
      CHUNK_SIZE: "67108864"
      # Opcional persistir directo a DB durante ingesta:
      # DB_HOST: db
      # DB_PORT: "5432"
      # DB_USER: core
      # DB_PASS: corepass
      # DB_NAME: corebank
    volumes:
      - "E:/:/mnt/e"

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: core
      POSTGRES_PASSWORD: corepass
      POSTGRES_DB: corebank
    ports: ["5432:5432"]
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata:
